name: Cloud Function Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy-cloud-function:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: auth
        uses: google-github-actions/auth@v0.4.1
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - id: setup-node
        users: actions/setup-node@v1
        with:
          node-version: 14
      
      - run: npm install
      - run: tsc

      - id: deploy
        uses: google-github-actions/deploy-cloud-functions@v0.6.0
        with:
          name: sam-tutorial-function
          runtime: nodejs14
          source_dir: dist
          entry_point: main